import aes.*;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.HexFormat;

/**
 * GUI for encrypting and decrypting files.
 * @author uninhm
 */
public class FileEncryptionGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FileEncryptionGUI.class.getName());

    private static final HexFormat hexFormat = HexFormat.of().withUpperCase();

    private Charset selectedCharset = StandardCharsets.UTF_8;
    private Padding selectedPadding = new PaddingPKCS7();
    private File loadedFile;

    /**
     * Creates a new form FileEncryptionGUI
     */
    public FileEncryptionGUI() {
        initComponents();

        // Document listener that updates the result preview on every change
        DocumentListener documentListener = new DocumentListener() {
            @Override
            public void removeUpdate(DocumentEvent e) {
                updateResult();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateResult();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateResult();
            }
        };

        // Auto-update result preview when file preview changes
        filePreviewArea.getDocument().addDocumentListener(documentListener);

        // Auto-update result preview when key changes
        keyField.getDocument().addDocumentListener(documentListener);
    }

    /**
     * Updates the result preview area with the result of the encryption/decryption.
     */
    private void updateResult() {
        try {
            AES aes = new AES(keyField.getText(), selectedPadding);

            if (binaryFileModeCheckbox.isSelected()) {
                if (loadedFile != null)
                    resultPreviewArea.setText("Press save to decrypt the binary file");
                else
                    resultPreviewArea.setText("");
            } else if (selectedModeButton.getText().equals("ENCRYPT")) {
                // Encrypt the file content and show the result as hex
                resultPreviewArea.setText(
                        hexFormat.formatHex(
                                aes.encrypt(filePreviewArea.getText(), selectedCharset)
                        )
                );
            } else {
                // Decrypt the file content and show the result
                resultPreviewArea.setText(
                        aes.decrypt(
                                hexFormat.parseHex(filePreviewArea.getText()),
                                selectedCharset
                        )
                );
            }

            // Enable the save button if no error occurred
            saveButton.setEnabled(true);
        } catch (InvalidKeySizeException ex) {
            resultPreviewArea.setText("Invalid key size");
            saveButton.setEnabled(false);
        } catch (IllegalArgumentException ex) {
            resultPreviewArea.setText("Invalid hexadecimal representation");
            saveButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        selectedModeLabel = new javax.swing.JLabel();
        selectedModeButton = new javax.swing.JButton();
        filePreviewLabel = new javax.swing.JLabel();
        filePreviewScrollPane = new javax.swing.JScrollPane();
        filePreviewArea = new javax.swing.JTextArea();
        resultPreviewLabel = new javax.swing.JLabel();
        resultPreviewScrollPane = new javax.swing.JScrollPane();
        resultPreviewArea = new javax.swing.JTextArea();
        keyLabel = new javax.swing.JLabel();
        keyField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        importFileItem = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        setPaddingMenu = new javax.swing.JMenu();
        pkcs7PaddingItem = new javax.swing.JMenuItem();
        zerosPaddingItem = new javax.swing.JMenuItem();
        setCharsetMenu = new javax.swing.JMenu();
        setCharsetUTF8Item = new javax.swing.JMenuItem();
        setCharsetUTF16Item = new javax.swing.JMenuItem();
        binaryFileModeCheckbox = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encrypt and decrypt files");
        setResizable(false);

        selectedModeLabel.setText("Selected mode:");
        selectedModeLabel.setToolTipText("");

        selectedModeButton.setText("ENCRYPT");
        selectedModeButton.addActionListener(this::selectedModeButtonActionPerformed);

        filePreviewLabel.setText("File preview:");

        filePreviewArea.setColumns(20);
        filePreviewArea.setLineWrap(true);
        filePreviewArea.setRows(5);
        filePreviewScrollPane.setViewportView(filePreviewArea);

        resultPreviewLabel.setText("Result preview:");

        resultPreviewArea.setColumns(20);
        resultPreviewArea.setLineWrap(true);
        resultPreviewArea.setRows(5);
        resultPreviewArea.setEnabled(false);
        resultPreviewScrollPane.setViewportView(resultPreviewArea);

        keyLabel.setText("Key:");

        keyField.setText("000102030405060708090a0b0c0d0e0f");

        saveButton.setText("Save");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
                contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(filePreviewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(filePreviewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(resultPreviewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(resultPreviewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                                .addComponent(selectedModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(selectedModeButton)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                                .addComponent(keyLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(keyField)))
                                                .addGap(6, 6, 6))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)
                                .addGap(7, 7, 7))
        );
        contentPaneLayout.setVerticalGroup(
                contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(selectedModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selectedModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filePreviewLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filePreviewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultPreviewLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultPreviewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(keyLabel)
                                        .addComponent(keyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(saveButton)
                                        .addComponent(cancelButton))
                                .addContainerGap())
        );

        fileMenu.setText("File");

        importFileItem.setText("Import file");
        importFileItem.addActionListener(this::importFileItemActionPerformed);
        fileMenu.add(importFileItem);

        menuBar.add(fileMenu);

        settingsMenu.setText("Settings");

        setPaddingMenu.setText("Set padding");

        pkcs7PaddingItem.setText("PKCS7");
        pkcs7PaddingItem.addActionListener(this::pkcs7PaddingItemActionPerformed);
        setPaddingMenu.add(pkcs7PaddingItem);

        zerosPaddingItem.setText("Zeros (deprecated)");
        zerosPaddingItem.addActionListener(this::zerosPaddingItemActionPerformed);
        setPaddingMenu.add(zerosPaddingItem);

        settingsMenu.add(setPaddingMenu);

        setCharsetMenu.setText("Set charset");

        setCharsetUTF8Item.setText("UTF-8");
        setCharsetUTF8Item.addActionListener(this::setCharsetUTF8ItemActionPerformed);
        setCharsetMenu.add(setCharsetUTF8Item);

        setCharsetUTF16Item.setText("UTF-16");
        setCharsetUTF16Item.addActionListener(this::setCharsetUTF16ItemActionPerformed);
        setCharsetMenu.add(setCharsetUTF16Item);

        settingsMenu.add(setCharsetMenu);

        binaryFileModeCheckbox.setText("Binary file mode");
        binaryFileModeCheckbox.addActionListener(this::binaryFileModeCheckboxActionPerformed);
        settingsMenu.add(binaryFileModeCheckbox);

        menuBar.add(settingsMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Opens a file dialog and loads the file into the file preview area.
     *
     * @param evt ActionEvent
     */
    private void importFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importFileItemActionPerformed
        // Open file dialog
        final JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File file = fc.getSelectedFile();

        if (file == null)
            return;

        // Try to load the file content into the file preview area
        try {
            if (binaryFileModeCheckbox.isSelected()) {
                filePreviewArea.setText("Binary file loaded.");
                loadedFile = file;
            } else if (selectedModeButton.getText().equals("ENCRYPT")) {
                // Read the file with the given charset
                filePreviewArea.setText(Files.readString(file.toPath(), selectedCharset));
            } else {
                // Read file as bytes and format as hex
                filePreviewArea.setText(hexFormat.formatHex(Files.readAllBytes(file.toPath())));
            }

            updateResult();
        } catch (IOException ex) {
            System.getLogger(FileEncryptionGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_importFileItemActionPerformed

    /**
     * Opens a file dialog and saves the result into the file.
     *
     * @param evt ActionEvent
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Open file dialog
        final JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);
        File file = fc.getSelectedFile();

        AES aes;
        try {
            aes = new AES(keyField.getText(), selectedPadding);

            FileOutputStream outputStream = new FileOutputStream(file);
            if (binaryFileModeCheckbox.isSelected()) {
                if (loadedFile == null)
                    resultPreviewArea.setText("No file loaded.");
                else if (selectedModeButton.getText().equals("ENCRYPT"))
                    // Write the encrypted file content to the file as bytes
                    outputStream.write(aes.encrypt(Files.readAllBytes(loadedFile.toPath())));
                else
                    outputStream.write(aes.decrypt(Files.readAllBytes(loadedFile.toPath())));
            } else if (selectedModeButton.getText().equals("ENCRYPT")) {
                // Write the encrypted file content to the file as bytes
                outputStream.write(aes.encrypt(filePreviewArea.getText(), selectedCharset));
            } else {
                // Write the decrypted file content to the file as bytes
                // We don't need to decode the characters because we copy the bytes directly to the file.
                outputStream.write(aes.decrypt(hexFormat.parseHex(filePreviewArea.getText())));
            }
            outputStream.close();
        } catch (InvalidKeySizeException ex) {
            System.out.println(ex.toString());
        } catch (IOException ex) {
            System.getLogger(FileEncryptionGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * Switches the selected mode between encryption and decryption.
     *
     * @param evt ActionEvent
     */
    private void selectedModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedModeButtonActionPerformed
        if (selectedModeButton.getText().equals("ENCRYPT"))
            selectedModeButton.setText("DECRYPT");
        else
            selectedModeButton.setText("ENCRYPT");
        updateResult();
    }//GEN-LAST:event_selectedModeButtonActionPerformed

    /**
     * Exits the application.
     * @param evt ActionEvent
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void setCharsetUTF16ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCharsetUTF16ItemActionPerformed
        selectedCharset = StandardCharsets.UTF_16;
        updateResult();
    }//GEN-LAST:event_setCharsetUTF16ItemActionPerformed

    private void pkcs7PaddingItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkcs7PaddingItemActionPerformed
        selectedPadding = new PaddingPKCS7();
        updateResult();
    }//GEN-LAST:event_pkcs7PaddingItemActionPerformed

    private void zerosPaddingItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerosPaddingItemActionPerformed
        selectedPadding = new PaddingZeros();
        updateResult();
    }//GEN-LAST:event_zerosPaddingItemActionPerformed

    private void setCharsetUTF8ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCharsetUTF8ItemActionPerformed
        selectedCharset = StandardCharsets.UTF_8;
        updateResult();
    }//GEN-LAST:event_setCharsetUTF8ItemActionPerformed

    private void binaryFileModeCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaryFileModeCheckboxActionPerformed
        filePreviewArea.setEnabled(!binaryFileModeCheckbox.isSelected());
    }//GEN-LAST:event_binaryFileModeCheckboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FileEncryptionGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem binaryFileModeCheckbox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel contentPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextArea filePreviewArea;
    private javax.swing.JLabel filePreviewLabel;
    private javax.swing.JScrollPane filePreviewScrollPane;
    private javax.swing.JMenuItem importFileItem;
    private javax.swing.JTextField keyField;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pkcs7PaddingItem;
    private javax.swing.JTextArea resultPreviewArea;
    private javax.swing.JLabel resultPreviewLabel;
    private javax.swing.JScrollPane resultPreviewScrollPane;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton selectedModeButton;
    private javax.swing.JLabel selectedModeLabel;
    private javax.swing.JMenu setCharsetMenu;
    private javax.swing.JMenuItem setCharsetUTF16Item;
    private javax.swing.JMenuItem setCharsetUTF8Item;
    private javax.swing.JMenu setPaddingMenu;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JMenuItem zerosPaddingItem;
    // End of variables declaration//GEN-END:variables
}
